# This file configures the hello-world app which serves public web traffic.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auto-gke
spec:
  replicas: 1
  selector:
    matchLabels:
      app: takotsubo
  template:
    metadata:
      labels:
        app: takotsubo
    spec:
      containers:
      - name: takotsubo-gke
        # Replace $LOCATION with your Artifact Registry location (e.g., us-west1).
        # Replace $GCLOUD_PROJECT with your project ID.
        image: asia-east1-docker.pkg.dev/groovy-groove-326910/hello-repo/takotsubo-gke:latest
        # This app listens on port 8080 for web traffic by default.
        ports:
        - containerPort: 8080
        env:
          - name: PORT
            value: "8080"
